# Generated by Django 2.0 on 2018-08-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slugUrl',
            field=models.SlugField(db_column='slug_url', default=''),
        ),
    ]
